// Auto-generated by LibreLane
module mac_mas_core(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input start,
  input mode,
  input[15:0] A,
  input[15:0] B,
  output ready,
  output[15:0] ACC_OUT
);
endmodule
